insert into PUB_BILLACTION ( PK_BILLACTION,PK_BILLTYPE,PK_BILLTYPEID,ACTION_TYPE,ACTIONNOTE,ACTIONNOTE2,ACTIONNOTE3,ACTIONNOTE4,ACTIONNOTE5,ACTIONNOTE6,ACTIONSTYLE,ACTIONSTYLEREMARK,ACTIONTYPE,CONSTRICTFLAG,CONTROLFLAG,FINISHFLAG,PUSHFLAG,SHOWHINT,SHOWHINT2,SHOWHINT3,SHOWHINT4,SHOWHINT5,SHOWHINT6,DR,TS ) values  ( '1001A11LCP00001J08VK','PU51','PU51',31,'保存',null,null,null,null,null,'0',null,'SAVEBASE','N','Y','Y',null,null,null,null,null,null,null,0,'2023-08-31 17:35:47' ) 
/

insert into PUB_BILLACTION ( PK_BILLACTION,PK_BILLTYPE,PK_BILLTYPEID,ACTION_TYPE,ACTIONNOTE,ACTIONNOTE2,ACTIONNOTE3,ACTIONNOTE4,ACTIONNOTE5,ACTIONNOTE6,ACTIONSTYLE,ACTIONSTYLEREMARK,ACTIONTYPE,CONSTRICTFLAG,CONTROLFLAG,FINISHFLAG,PUSHFLAG,SHOWHINT,SHOWHINT2,SHOWHINT3,SHOWHINT4,SHOWHINT5,SHOWHINT6,DR,TS ) values  ( '1001A11LCP00001J08VL','PU51','PU51',10,'提交',null,null,null,null,null,'3',null,'SAVE','N','Y','Y',null,null,null,null,null,null,null,0,'2023-08-31 17:35:47' ) 
/

insert into PUB_BILLACTION ( PK_BILLACTION,PK_BILLTYPE,PK_BILLTYPEID,ACTION_TYPE,ACTIONNOTE,ACTIONNOTE2,ACTIONNOTE3,ACTIONNOTE4,ACTIONNOTE5,ACTIONNOTE6,ACTIONSTYLE,ACTIONSTYLEREMARK,ACTIONTYPE,CONSTRICTFLAG,CONTROLFLAG,FINISHFLAG,PUSHFLAG,SHOWHINT,SHOWHINT2,SHOWHINT3,SHOWHINT4,SHOWHINT5,SHOWHINT6,DR,TS ) values  ( '1001A11LCP00001J08VM','PU51','PU51',13,'收回',null,null,null,null,null,'3',null,'UNSAVE','N','Y','Y',null,null,null,null,null,null,null,0,'2023-08-31 17:35:47' ) 
/

insert into PUB_BILLACTION ( PK_BILLACTION,PK_BILLTYPE,PK_BILLTYPEID,ACTION_TYPE,ACTIONNOTE,ACTIONNOTE2,ACTIONNOTE3,ACTIONNOTE4,ACTIONNOTE5,ACTIONNOTE6,ACTIONSTYLE,ACTIONSTYLEREMARK,ACTIONTYPE,CONSTRICTFLAG,CONTROLFLAG,FINISHFLAG,PUSHFLAG,SHOWHINT,SHOWHINT2,SHOWHINT3,SHOWHINT4,SHOWHINT5,SHOWHINT6,DR,TS ) values  ( '1001A11LCP00001J08VN','PU51','PU51',11,'审批',null,null,null,null,null,'2',null,'APPROVE','N','Y','Y',null,null,null,null,null,null,null,0,'2023-08-31 17:35:47' ) 
/

insert into PUB_BILLACTION ( PK_BILLACTION,PK_BILLTYPE,PK_BILLTYPEID,ACTION_TYPE,ACTIONNOTE,ACTIONNOTE2,ACTIONNOTE3,ACTIONNOTE4,ACTIONNOTE5,ACTIONNOTE6,ACTIONSTYLE,ACTIONSTYLEREMARK,ACTIONTYPE,CONSTRICTFLAG,CONTROLFLAG,FINISHFLAG,PUSHFLAG,SHOWHINT,SHOWHINT2,SHOWHINT3,SHOWHINT4,SHOWHINT5,SHOWHINT6,DR,TS ) values  ( '1001A11LCP00001J08VO','PU51','PU51',12,'取消审批',null,null,null,null,null,'3',null,'UNAPPROVE','N','Y','Y',null,null,null,null,null,null,null,0,'2023-08-31 17:35:47' ) 
/

