insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'region_CjmMaster_Add_Group','',null,null,'1001A1100000001IFO73',null,'Y','4004800H1_region_CjmMaster',1,'buttongroup','common',null,null,'','button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001IIVLO',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'Save','保存',null,null,'1001A1100000001IFO73',null,'Y','4004800H1_region_CjmMaster',2,'general_btn','common','region_CjmMaster_Add_Group',null,'Ctrl+S','button_main',null,null,null,null,null,null,null,'1001A11LCP00001IIVLP',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'SaveAdd','保存新增',null,null,'1001A1100000001IFO73',null,'Y','4004800H1_region_CjmMaster',3,'general_btn','common','region_CjmMaster_Add_Group',null,'Alt+S','button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001IIVLQ',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'Copy','复制',null,null,'1001A1100000001IFO73',null,'Y','4004800H1_region_CjmMaster',4,'general_btn','common',null,null,'Alt+C','button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001IIVLR',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'Cancel','取消',null,null,'1001A1100000001IFO73',null,'Y','4004800H1_region_CjmMaster',5,'general_btn','common',null,null,'Alt+Q','button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001IIVLS',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'Enable','启用',null,null,'1001A1100000001IFO73',null,'Y','4004800H1_region_CjmMaster',6,'divider','common',null,null,null,'button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001IIVLT',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'enablestate_Group','',null,null,'1001A1100000001IFO73',null,'Y','4004800H1_region_CjmMaster',7,'buttongroup','common','Enable',null,'','button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001IIVLU',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'Disable','停用',null,null,'1001A1100000001IFO73',null,'Y','4004800H1_region_CjmMaster',8,'general_btn','common','enablestate_Group',null,null,'button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001IIVLV',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'fs_group_add','新建分组',null,null,'1001A1100000001IFO73',null,'Y','4004800H1_region_CjmMaster',9,'general_btn','ncuploader_modal-area',null,null,null,'button_main',null,null,null,null,null,null,null,'1001A11LCP00001IIVLW',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'fs_browse','预览',null,null,'1001A1100000001IFO73',null,'Y','4004800H1_region_CjmMaster',10,'general_btn','ncuploader_modal-area',null,null,null,'button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001IIVLX',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'fs_delete','删除',null,null,'1001A1100000001IFO73',null,'Y','4004800H1_region_CjmMaster',11,'general_btn','ncuploader_modal-area',null,null,null,'button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001IIVLY',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'fs_download','下载',null,null,'1001A1100000001IFO73',null,'Y','4004800H1_region_CjmMaster',12,'general_btn','ncuploader_modal-area',null,null,null,'button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001IIVLZ',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'fs_edit','修改',null,null,'1001A1100000001IFO73',null,'Y','4004800H1_region_CjmMaster',13,'general_btn','ncuploader_modal-area',null,null,null,'button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001IIVM0',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'fs_group_edit','组名修改',null,null,'1001A1100000001IFO73',null,'Y','4004800H1_region_CjmMaster',14,'general_btn','ncuploader_modal-area',null,null,null,'button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001IIVM1',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'fs_group_delete','组名删除',null,null,'1001A1100000001IFO73',null,'Y','4004800H1_region_CjmMaster',15,'general_btn','ncuploader_modal-area',null,null,null,'button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001IIVM2',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'fs_heigh_meter','高拍仪',null,null,'1001A1100000001IFO73',null,'Y','4004800H1_region_CjmMaster',16,'general_btn','ncuploader_modal-area',null,null,null,'button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001IIVM3',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'fs_move','移动',null,null,'1001A1100000001IFO73',null,'Y','4004800H1_region_CjmMaster',17,'general_btn','ncuploader_modal-area',null,null,null,'button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001IIVM4',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'fs_rename','重命名',null,null,'1001A1100000001IFO73',null,'Y','4004800H1_region_CjmMaster',18,'general_btn','ncuploader_modal-area',null,null,null,'button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001IIVM5',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'fs_upload','上传',null,null,'1001A1100000001IFO73',null,'Y','4004800H1_region_CjmMaster',19,'general_btn','ncuploader_modal-area',null,null,null,'button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001IIVM6',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'fs_upload_url','上传url',null,null,'1001A1100000001IFO73',null,'Y','4004800H1_region_CjmMaster',20,'general_btn','ncuploader_modal-area',null,null,null,'button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001IIVM7',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'More','更多',null,null,'1001A1100000001IFO73',null,'Y','4004800H1_region_CjmMaster',21,'more','common',null,null,null,'button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001IIVM8',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'Attachment_Group','辅助功能',null,null,'1001A1100000001IFO73',null,'Y','4004800H1_region_CjmMaster',22,'buttongroup','common','More',null,'','button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001IIVM9',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'Attachment','附件管理',null,null,'1001A1100000001IFO73',null,'Y','4004800H1_region_CjmMaster',23,'general_btn','common','Attachment_Group',null,'Alt+D','button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001IIVMA',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'PrintAndOutput_Group','打印',null,null,'1001A1100000001IFO73',null,'Y','4004800H1_region_CjmMaster',24,'buttongroup','common','More',null,'','button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001IIVMC',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'Print','打印',null,null,'1001A1100000001IFO73',null,'Y','4004800H1_region_CjmMaster',25,'general_btn','common','PrintAndOutput_Group',null,'Ctrl+P','button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001IIVMD',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'Output','输出',null,null,'1001A1100000001IFO73',null,'Y','4004800H1_region_CjmMaster',26,'general_btn','common','PrintAndOutput_Group',null,'Ctrl+W','button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001IIVME',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'ImportAndExport_Group','导入',null,null,'1001A1100000001IFO73',null,'Y','4004800H1_region_CjmMaster',27,'buttongroup','common','More',null,'','button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001IIVMG',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'Import','导入',null,null,'1001A1100000001IFO73',null,'Y','4004800H1_region_CjmMaster',28,'general_btn','common','ImportAndExport_Group',null,'Ctrl+Alt+E','button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001IIVMH',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'Export','导出',null,null,'1001A1100000001IFO73',null,'Y','4004800H1_region_CjmMaster',29,'general_btn','common','ImportAndExport_Group',null,'ctrl+alt+c','button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001IIVMI',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'Refresh','',null,null,'1001A1100000001IFO73',null,'Y','4004800H1_region_CjmMaster',30,'general_btn','common',null,null,'F5','button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001IIVMJ',0,null ) 
/

