insert into PUB_VOCHANGE ( BACKCLASS,DEST_BILLTYPE,DEST_SYSTYPE,DEST_TRANSTYPE,FRONTCLASS,PK_BUSITYPE,PK_GROUP,PK_VOCHANGE,RESERVEBACKCLASS,RESERVEFRONTCLASS,SRC_APPCODE,SRC_BILLTYPE,SRC_BILLUI,SRC_NCCQUERYCLASS,SRC_NODEKEY,SRC_PAGECODE,SRC_QRYTEMPLATE,SRC_SYSTYPE,SRC_TRANSTYPE,UPGRADEEXCLASS,TS,DR ) values  ( null,'TESTMD24','uapbd','~',null,'~','global00000000000000','1001A11LCP000007JZXT',null,null,null,'10KH',null,null,null,null,null,'UAPBD','~',null,'2023-06-25 10:25:06',null ) 
/

