insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'fs_group_add','新建分组',null,null,'1001A11LCP00001IZLON',null,'Y','4004900H1L_order_cjmMasterL',1,'general_btn','ncuploader_modal-area',null,null,null,'button_main',null,null,null,null,null,null,null,'1001A11LCP00001J0910',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'fs_browse','预览',null,null,'1001A11LCP00001IZLON',null,'Y','4004900H1L_order_cjmMasterL',2,'general_btn','ncuploader_modal-area',null,null,null,'button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001J0911',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'fs_delete','删除',null,null,'1001A11LCP00001IZLON',null,'Y','4004900H1L_order_cjmMasterL',3,'general_btn','ncuploader_modal-area',null,null,null,'button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001J0912',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'fs_download','下载',null,null,'1001A11LCP00001IZLON',null,'Y','4004900H1L_order_cjmMasterL',4,'general_btn','ncuploader_modal-area',null,null,null,'button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001J0913',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'fs_edit','修改',null,null,'1001A11LCP00001IZLON',null,'Y','4004900H1L_order_cjmMasterL',5,'general_btn','ncuploader_modal-area',null,null,null,'button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001J0914',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'fs_group_edit','组名修改',null,null,'1001A11LCP00001IZLON',null,'Y','4004900H1L_order_cjmMasterL',6,'general_btn','ncuploader_modal-area',null,null,null,'button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001J0915',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'fs_group_delete','组名删除',null,null,'1001A11LCP00001IZLON',null,'Y','4004900H1L_order_cjmMasterL',7,'general_btn','ncuploader_modal-area',null,null,null,'button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001J0916',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'fs_heigh_meter','高拍仪',null,null,'1001A11LCP00001IZLON',null,'Y','4004900H1L_order_cjmMasterL',8,'general_btn','ncuploader_modal-area',null,null,null,'button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001J0917',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'fs_move','移动',null,null,'1001A11LCP00001IZLON',null,'Y','4004900H1L_order_cjmMasterL',9,'general_btn','ncuploader_modal-area',null,null,null,'button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001J0918',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'fs_rename','重命名',null,null,'1001A11LCP00001IZLON',null,'Y','4004900H1L_order_cjmMasterL',10,'general_btn','ncuploader_modal-area',null,null,null,'button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001J0919',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'fs_upload','上传',null,null,'1001A11LCP00001IZLON',null,'Y','4004900H1L_order_cjmMasterL',11,'general_btn','ncuploader_modal-area',null,null,null,'button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001J091A',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'fs_upload_url','上传url',null,null,'1001A11LCP00001IZLON',null,'Y','4004900H1L_order_cjmMasterL',12,'general_btn','ncuploader_modal-area',null,null,null,'button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001J091B',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'Attachment','附件管理',null,null,'1001A11LCP00001IZLON',null,'Y','4004900H1L_order_cjmMasterL',1,'general_btn','common',null,null,'Alt+D','button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001J097I',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'Refresh','',null,null,'1001A11LCP00001IZLON',null,'Y','4004900H1L_order_cjmMasterL',2,'general_btn','common',null,null,'F5','button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001J097J',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'order_cjmSlave0_AddLine_Group','',null,null,'1001A11LCP00001IZLON',null,'Y','4004900H1L_order_cjmMasterL',3,'buttongroup','order_cjmSlave0',null,null,'','button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001J097K',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'order_cjmSlave0_AddLine','增行',null,null,'1001A11LCP00001IZLON',null,'Y','4004900H1L_order_cjmMasterL',4,'general_btn','order_cjmSlave0','order_cjmSlave0_AddLine_Group',null,'Alt+N','button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001J097L',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'order_cjmSlave0_CopyLine','复制',null,null,'1001A11LCP00001IZLON',null,'Y','4004900H1L_order_cjmMasterL',5,'general_btn','order_cjmSlave0','order_cjmSlave0_AddLine_Group',null,'alt+c','button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001J097M',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'order_cjmSlave0_DelLine','删行',null,null,'1001A11LCP00001IZLON',null,'Y','4004900H1L_order_cjmMasterL',6,'general_btn','order_cjmSlave0','order_cjmSlave0_AddLine_Group',null,'alt+del','button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001J097N',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'order_cjmSlave0_Past_Group','',null,null,'1001A11LCP00001IZLON',null,'Y','4004900H1L_order_cjmMasterL',7,'buttongroup','order_cjmSlave0',null,null,'','button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001J097O',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'order_cjmSlave0_PastEndLine','粘贴到末行',null,null,'1001A11LCP00001IZLON',null,'Y','4004900H1L_order_cjmMasterL',8,'general_btn','order_cjmSlave0','order_cjmSlave0_Past_Group',null,'Ctrl+Alt+V','button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001J097P',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'order_cjmSlave0_CopyCancelLine','取消',null,null,'1001A11LCP00001IZLON',null,'Y','4004900H1L_order_cjmMasterL',9,'general_btn','order_cjmSlave0','order_cjmSlave0_Past_Group',null,null,'button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001J097Q',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'order_cjmSlave0_Opr_DelLine','删行',null,null,'1001A11LCP00001IZLON',null,'Y','4004900H1L_order_cjmMasterL',10,'general_btn','order_cjmSlave0_Opr',null,null,'alt+del','button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001J097R',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'order_cjmSlave0_Opr_ExpandLine','展开',null,null,'1001A11LCP00001IZLON',null,'Y','4004900H1L_order_cjmMasterL',11,'general_btn','order_cjmSlave0_Opr',null,null,'F4','button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001J097S',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'order_cjmSlave0_Opr_CopyLine','复制',null,null,'1001A11LCP00001IZLON',null,'Y','4004900H1L_order_cjmMasterL',12,'general_btn','order_cjmSlave0_Opr',null,null,'alt+c','button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001J097T',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'order_cjmSlave0_Opr_PastNextLine','粘贴至此',null,null,'1001A11LCP00001IZLON',null,'Y','4004900H1L_order_cjmMasterL',13,'general_btn','order_cjmSlave0_Opr',null,null,'Alt+V','button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001J097U',0,null ) 
/

