insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'office_CjmMaster_Add_Group','',null,null,'1001A1100000001IIVMU',null,'Y','4004800M1_office_CjmMaster',1,'buttongroup','common',null,null,'','button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001IIVRK',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'Add','新增',null,null,'1001A1100000001IIVMU',null,'Y','4004800M1_office_CjmMaster',2,'general_btn','common','office_CjmMaster_Add_Group',null,'Ctrl+/','button_main',null,null,null,null,null,null,null,'1001A11LCP00001IIVRL',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'Edit','修改',null,null,'1001A1100000001IIVMU',null,'Y','4004800M1_office_CjmMaster',3,'general_btn','common','office_CjmMaster_Add_Group',null,'Alt+P','button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001IIVRM',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'Copy','复制',null,null,'1001A1100000001IIVMU',null,'Y','4004800M1_office_CjmMaster',4,'general_btn','common','office_CjmMaster_Add_Group',null,'Alt+C','button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001IIVRN',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'Delete','删除',null,null,'1001A1100000001IIVMU',null,'Y','4004800M1_office_CjmMaster',5,'general_btn','common','office_CjmMaster_Add_Group',null,'Ctrl+Del','button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001IIVRO',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'office_CjmMaster_Save_Group','',null,null,'1001A1100000001IIVMU',null,'Y','4004800M1_office_CjmMaster',6,'buttongroup','common',null,null,'','button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001IIVRP',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'Save','保存',null,null,'1001A1100000001IIVMU',null,'Y','4004800M1_office_CjmMaster',7,'general_btn','common','office_CjmMaster_Save_Group',null,'Ctrl+S','button_main',null,null,null,null,null,null,null,'1001A11LCP00001IIVRQ',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'SaveAdd','保存新增',null,null,'1001A1100000001IIVMU',null,'Y','4004800M1_office_CjmMaster',8,'general_btn','common','office_CjmMaster_Save_Group',null,'Alt+S','button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001IIVRR',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'Edit','修改',null,null,'1001A1100000001IIVMU',null,'Y','4004800M1_office_CjmMaster',9,'general_btn','tablebtn',null,null,'Alt+P','button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001IIVRS',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'Delete','删除',null,null,'1001A1100000001IIVMU',null,'Y','4004800M1_office_CjmMaster',10,'general_btn','tablebtn',null,null,'Ctrl+Del','button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001IIVRT',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'Cancel','取消',null,null,'1001A1100000001IIVMU',null,'Y','4004800M1_office_CjmMaster',11,'general_btn','common',null,null,'Alt+Q','button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001IIVRU',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'fs_group_add','新建分组',null,null,'1001A1100000001IIVMU',null,'Y','4004800M1_office_CjmMaster',12,'general_btn','ncuploader_modal-area',null,null,null,'button_main',null,null,null,null,null,null,null,'1001A11LCP00001IIVRV',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'fs_browse','预览',null,null,'1001A1100000001IIVMU',null,'Y','4004800M1_office_CjmMaster',13,'general_btn','ncuploader_modal-area',null,null,null,'button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001IIVRW',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'fs_delete','删除',null,null,'1001A1100000001IIVMU',null,'Y','4004800M1_office_CjmMaster',14,'general_btn','ncuploader_modal-area',null,null,null,'button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001IIVRX',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'fs_download','下载',null,null,'1001A1100000001IIVMU',null,'Y','4004800M1_office_CjmMaster',15,'general_btn','ncuploader_modal-area',null,null,null,'button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001IIVRY',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'fs_edit','修改',null,null,'1001A1100000001IIVMU',null,'Y','4004800M1_office_CjmMaster',16,'general_btn','ncuploader_modal-area',null,null,null,'button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001IIVRZ',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'fs_group_edit','组名修改',null,null,'1001A1100000001IIVMU',null,'Y','4004800M1_office_CjmMaster',17,'general_btn','ncuploader_modal-area',null,null,null,'button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001IIVS0',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'fs_group_delete','组名删除',null,null,'1001A1100000001IIVMU',null,'Y','4004800M1_office_CjmMaster',18,'general_btn','ncuploader_modal-area',null,null,null,'button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001IIVS1',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'fs_heigh_meter','高拍仪',null,null,'1001A1100000001IIVMU',null,'Y','4004800M1_office_CjmMaster',19,'general_btn','ncuploader_modal-area',null,null,null,'button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001IIVS2',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'fs_move','移动',null,null,'1001A1100000001IIVMU',null,'Y','4004800M1_office_CjmMaster',20,'general_btn','ncuploader_modal-area',null,null,null,'button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001IIVS3',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'fs_rename','重命名',null,null,'1001A1100000001IIVMU',null,'Y','4004800M1_office_CjmMaster',21,'general_btn','ncuploader_modal-area',null,null,null,'button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001IIVS4',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'fs_upload','上传',null,null,'1001A1100000001IIVMU',null,'Y','4004800M1_office_CjmMaster',22,'general_btn','ncuploader_modal-area',null,null,null,'button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001IIVS5',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'fs_upload_url','上传url',null,null,'1001A1100000001IIVMU',null,'Y','4004800M1_office_CjmMaster',23,'general_btn','ncuploader_modal-area',null,null,null,'button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001IIVS6',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'More','更多',null,null,'1001A1100000001IIVMU',null,'Y','4004800M1_office_CjmMaster',24,'more','common',null,null,null,'button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001IIVS7',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'Attachment_Group','辅助功能',null,null,'1001A1100000001IIVMU',null,'Y','4004800M1_office_CjmMaster',25,'buttongroup','common','More',null,'','button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001IIVS8',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'Attachment','附件管理',null,null,'1001A1100000001IIVMU',null,'Y','4004800M1_office_CjmMaster',26,'general_btn','common','Attachment_Group',null,'Alt+D','button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001IIVS9',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'PrintAndOutput_Group','打印',null,null,'1001A1100000001IIVMU',null,'Y','4004800M1_office_CjmMaster',27,'buttongroup','common','More',null,'','button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001IIVSB',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'Print','打印',null,null,'1001A1100000001IIVMU',null,'Y','4004800M1_office_CjmMaster',28,'general_btn','common','PrintAndOutput_Group',null,'Ctrl+P','button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001IIVSC',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'Output','输出',null,null,'1001A1100000001IIVMU',null,'Y','4004800M1_office_CjmMaster',29,'general_btn','common','PrintAndOutput_Group',null,'Ctrl+W','button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001IIVSD',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'ImportAndExport_Group','导入',null,null,'1001A1100000001IIVMU',null,'Y','4004800M1_office_CjmMaster',30,'buttongroup','common','More',null,'','button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001IIVSF',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'Import','导入',null,null,'1001A1100000001IIVMU',null,'Y','4004800M1_office_CjmMaster',31,'general_btn','common','ImportAndExport_Group',null,'Ctrl+Alt+E','button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001IIVSG',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'Export','导出',null,null,'1001A1100000001IIVMU',null,'Y','4004800M1_office_CjmMaster',32,'general_btn','common','ImportAndExport_Group',null,'ctrl+alt+c','button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001IIVSH',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'Refresh','',null,null,'1001A1100000001IIVMU',null,'Y','4004800M1_office_CjmMaster',33,'general_btn','common',null,null,'F5','button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001IIVSI',0,null ) 
/

