insert into PUB_BILLACTION ( PK_BILLACTION,PK_BILLTYPE,PK_BILLTYPEID,ACTION_TYPE,ACTIONNOTE,ACTIONNOTE2,ACTIONNOTE3,ACTIONNOTE4,ACTIONNOTE5,ACTIONNOTE6,ACTIONSTYLE,ACTIONSTYLEREMARK,ACTIONTYPE,CONSTRICTFLAG,CONTROLFLAG,FINISHFLAG,PUSHFLAG,SHOWHINT,SHOWHINT2,SHOWHINT3,SHOWHINT4,SHOWHINT5,SHOWHINT6,DR,TS ) values  ( '1001A11LCP000007JZXE','TESTMD24','TESTMD24',31,'保存',null,null,null,null,null,'0',null,'SAVEBASE','N','Y','Y',null,null,null,null,null,null,null,0,'2023-06-25 10:25:06' ) 
/

insert into PUB_BILLACTION ( PK_BILLACTION,PK_BILLTYPE,PK_BILLTYPEID,ACTION_TYPE,ACTIONNOTE,ACTIONNOTE2,ACTIONNOTE3,ACTIONNOTE4,ACTIONNOTE5,ACTIONNOTE6,ACTIONSTYLE,ACTIONSTYLEREMARK,ACTIONTYPE,CONSTRICTFLAG,CONTROLFLAG,FINISHFLAG,PUSHFLAG,SHOWHINT,SHOWHINT2,SHOWHINT3,SHOWHINT4,SHOWHINT5,SHOWHINT6,DR,TS ) values  ( '1001A11LCP000007JZXF','TESTMD24','TESTMD24',10,'提交',null,null,null,null,null,'3',null,'SAVE','N','Y','Y',null,null,null,null,null,null,null,0,'2023-06-25 10:25:06' ) 
/

insert into PUB_BILLACTION ( PK_BILLACTION,PK_BILLTYPE,PK_BILLTYPEID,ACTION_TYPE,ACTIONNOTE,ACTIONNOTE2,ACTIONNOTE3,ACTIONNOTE4,ACTIONNOTE5,ACTIONNOTE6,ACTIONSTYLE,ACTIONSTYLEREMARK,ACTIONTYPE,CONSTRICTFLAG,CONTROLFLAG,FINISHFLAG,PUSHFLAG,SHOWHINT,SHOWHINT2,SHOWHINT3,SHOWHINT4,SHOWHINT5,SHOWHINT6,DR,TS ) values  ( '1001A11LCP000007JZXG','TESTMD24','TESTMD24',13,'收回',null,null,null,null,null,'3',null,'UNSAVE','N','Y','Y',null,null,null,null,null,null,null,0,'2023-06-25 10:25:06' ) 
/

insert into PUB_BILLACTION ( PK_BILLACTION,PK_BILLTYPE,PK_BILLTYPEID,ACTION_TYPE,ACTIONNOTE,ACTIONNOTE2,ACTIONNOTE3,ACTIONNOTE4,ACTIONNOTE5,ACTIONNOTE6,ACTIONSTYLE,ACTIONSTYLEREMARK,ACTIONTYPE,CONSTRICTFLAG,CONTROLFLAG,FINISHFLAG,PUSHFLAG,SHOWHINT,SHOWHINT2,SHOWHINT3,SHOWHINT4,SHOWHINT5,SHOWHINT6,DR,TS ) values  ( '1001A11LCP000007JZXH','TESTMD24','TESTMD24',11,'审批',null,null,null,null,null,'2',null,'APPROVE','N','Y','Y',null,null,null,null,null,null,null,0,'2023-06-25 10:25:06' ) 
/

insert into PUB_BILLACTION ( PK_BILLACTION,PK_BILLTYPE,PK_BILLTYPEID,ACTION_TYPE,ACTIONNOTE,ACTIONNOTE2,ACTIONNOTE3,ACTIONNOTE4,ACTIONNOTE5,ACTIONNOTE6,ACTIONSTYLE,ACTIONSTYLEREMARK,ACTIONTYPE,CONSTRICTFLAG,CONTROLFLAG,FINISHFLAG,PUSHFLAG,SHOWHINT,SHOWHINT2,SHOWHINT3,SHOWHINT4,SHOWHINT5,SHOWHINT6,DR,TS ) values  ( '1001A11LCP000007JZXI','TESTMD24','TESTMD24',12,'取消审批',null,null,null,null,null,'3',null,'UNAPPROVE','N','Y','Y',null,null,null,null,null,null,null,0,'2023-06-25 10:25:06' ) 
/

