insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'order_cjmMaster_Add_Group','',null,null,'1001A1100000001IYV0D',null,'Y','4004900H1_order_cjmMaster',1,'buttongroup','common',null,null,'','button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001J095M',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'Add','新增',null,null,'1001A1100000001IYV0D',null,'Y','4004900H1_order_cjmMaster',2,'general_btn','common','order_cjmMaster_Add_Group',null,'Ctrl+/','button_main',null,null,null,null,null,null,null,'1001A11LCP00001J095N',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'Edit','修改',null,null,'1001A1100000001IYV0D',null,'Y','4004900H1_order_cjmMaster',3,'general_btn','common','order_cjmMaster_Add_Group',null,'Alt+P','button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001J095O',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'Copy','复制',null,null,'1001A1100000001IYV0D',null,'Y','4004900H1_order_cjmMaster',4,'general_btn','common','order_cjmMaster_Add_Group',null,'Alt+C','button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001J095P',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'Delete','删除',null,null,'1001A1100000001IYV0D',null,'Y','4004900H1_order_cjmMaster',5,'general_btn','common','order_cjmMaster_Add_Group',null,'Ctrl+Del','button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001J095Q',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'order_cjmMaster_Save_Group','',null,null,'1001A1100000001IYV0D',null,'Y','4004900H1_order_cjmMaster',6,'buttongroup','common',null,null,'','button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001J095R',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'Save','保存',null,null,'1001A1100000001IYV0D',null,'Y','4004900H1_order_cjmMaster',7,'general_btn','common','order_cjmMaster_Save_Group',null,'Ctrl+S','button_main',null,null,null,null,null,null,null,'1001A11LCP00001J095S',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'SaveAdd','保存新增',null,null,'1001A1100000001IYV0D',null,'Y','4004900H1_order_cjmMaster',8,'general_btn','common','order_cjmMaster_Save_Group',null,'Alt+S','button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001J095T',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'Cancel','取消',null,null,'1001A1100000001IYV0D',null,'Y','4004900H1_order_cjmMaster',9,'general_btn','common',null,null,'Alt+Q','button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001J095U',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'order_cjmSlave0_AddLine_Group','',null,null,'1001A1100000001IYV0D',null,'Y','4004900H1_order_cjmMaster',10,'buttongroup','order_cjmSlave0Sub',null,null,'','button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001J095V',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'order_cjmSlave0Sub_AddLine','增行',null,null,'1001A1100000001IYV0D',null,'Y','4004900H1_order_cjmMaster',11,'general_btn','order_cjmSlave0Sub','order_cjmSlave0_AddLine_Group',null,'Alt+N','button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001J095W',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'order_cjmSlave0Sub_CopyLine','复制',null,null,'1001A1100000001IYV0D',null,'Y','4004900H1_order_cjmMaster',12,'general_btn','order_cjmSlave0Sub','order_cjmSlave0_AddLine_Group',null,'alt+c','button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001J095X',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'order_cjmSlave0Sub_DelLine','删行',null,null,'1001A1100000001IYV0D',null,'Y','4004900H1_order_cjmMaster',13,'general_btn','order_cjmSlave0Sub','order_cjmSlave0_AddLine_Group',null,'alt+del','button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001J095Y',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'order_cjmSlave0_Past_Group','',null,null,'1001A1100000001IYV0D',null,'Y','4004900H1_order_cjmMaster',14,'buttongroup','order_cjmSlave0Sub',null,null,'','button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001J095Z',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'order_cjmSlave0Sub_PastEndLine','粘贴到末行',null,null,'1001A1100000001IYV0D',null,'Y','4004900H1_order_cjmMaster',15,'general_btn','order_cjmSlave0Sub','order_cjmSlave0_Past_Group',null,'Ctrl+Alt+V','button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001J0960',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'order_cjmSlave0Sub_CopyCancelLine','取消',null,null,'1001A1100000001IYV0D',null,'Y','4004900H1_order_cjmMaster',16,'general_btn','order_cjmSlave0Sub','order_cjmSlave0_Past_Group',null,null,'button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001J0961',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'order_cjmSlave0Sub_DelLineOpr','删除',null,null,'1001A1100000001IYV0D',null,'Y','4004900H1_order_cjmMaster',17,'general_btn','order_cjmSlave0SubOpr',null,null,'alt+del','button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001J0962',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'order_cjmSlave0Sub_ExpandLineOpr','展开',null,null,'1001A1100000001IYV0D',null,'Y','4004900H1_order_cjmMaster',18,'general_btn','order_cjmSlave0SubOpr',null,null,'f4','button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001J0963',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'order_cjmSlave0Sub_CopyLineOpr','复制行',null,null,'1001A1100000001IYV0D',null,'Y','4004900H1_order_cjmMaster',19,'general_btn','order_cjmSlave0SubOpr',null,null,'Alt+C','button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001J0964',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'order_cjmSlave0Sub_PastNextLineOpr','粘贴至此',null,null,'1001A1100000001IYV0D',null,'Y','4004900H1_order_cjmMaster',20,'general_btn','order_cjmSlave0SubOpr',null,null,'alt+v','button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001J0965',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'Commit','提交',null,null,'1001A1100000001IYV0D',null,'Y','4004900H1_order_cjmMaster',21,'divider','common',null,null,'Alt+B','button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001J0966',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'pu51_Group','',null,null,'1001A1100000001IYV0D',null,'Y','4004900H1_order_cjmMaster',22,'buttongroup','common','Commit',null,'','button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001J0967',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'UnCommit','收回',null,null,'1001A1100000001IYV0D',null,'Y','4004900H1_order_cjmMaster',23,'general_btn','common','pu51_Group',null,'Ctrl+B','button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001J0968',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'fs_group_add','新建分组',null,null,'1001A1100000001IYV0D',null,'Y','4004900H1_order_cjmMaster',24,'general_btn','ncuploader_modal-area',null,null,null,'button_main',null,null,null,null,null,null,null,'1001A11LCP00001J0969',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'fs_browse','预览',null,null,'1001A1100000001IYV0D',null,'Y','4004900H1_order_cjmMaster',25,'general_btn','ncuploader_modal-area',null,null,null,'button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001J096A',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'fs_delete','删除',null,null,'1001A1100000001IYV0D',null,'Y','4004900H1_order_cjmMaster',26,'general_btn','ncuploader_modal-area',null,null,null,'button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001J096B',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'fs_download','下载',null,null,'1001A1100000001IYV0D',null,'Y','4004900H1_order_cjmMaster',27,'general_btn','ncuploader_modal-area',null,null,null,'button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001J096C',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'fs_edit','修改',null,null,'1001A1100000001IYV0D',null,'Y','4004900H1_order_cjmMaster',28,'general_btn','ncuploader_modal-area',null,null,null,'button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001J096D',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'fs_group_edit','组名修改',null,null,'1001A1100000001IYV0D',null,'Y','4004900H1_order_cjmMaster',29,'general_btn','ncuploader_modal-area',null,null,null,'button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001J096E',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'fs_group_delete','组名删除',null,null,'1001A1100000001IYV0D',null,'Y','4004900H1_order_cjmMaster',30,'general_btn','ncuploader_modal-area',null,null,null,'button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001J096F',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'fs_heigh_meter','高拍仪',null,null,'1001A1100000001IYV0D',null,'Y','4004900H1_order_cjmMaster',31,'general_btn','ncuploader_modal-area',null,null,null,'button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001J096G',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'fs_move','移动',null,null,'1001A1100000001IYV0D',null,'Y','4004900H1_order_cjmMaster',32,'general_btn','ncuploader_modal-area',null,null,null,'button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001J096H',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'fs_rename','重命名',null,null,'1001A1100000001IYV0D',null,'Y','4004900H1_order_cjmMaster',33,'general_btn','ncuploader_modal-area',null,null,null,'button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001J096I',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'fs_upload','上传',null,null,'1001A1100000001IYV0D',null,'Y','4004900H1_order_cjmMaster',34,'general_btn','ncuploader_modal-area',null,null,null,'button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001J096J',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'fs_upload_url','上传url',null,null,'1001A1100000001IYV0D',null,'Y','4004900H1_order_cjmMaster',35,'general_btn','ncuploader_modal-area',null,null,null,'button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001J096K',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'More','更多',null,null,'1001A1100000001IYV0D',null,'Y','4004900H1_order_cjmMaster',36,'more','common',null,null,null,'button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001J096L',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'Attachment_Group','辅助功能',null,null,'1001A1100000001IYV0D',null,'Y','4004900H1_order_cjmMaster',37,'buttongroup','common','More',null,'','button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001J096M',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'Attachment','附件管理',null,null,'1001A1100000001IYV0D',null,'Y','4004900H1_order_cjmMaster',38,'general_btn','common','Attachment_Group',null,'Alt+D','button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001J096N',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'PrintAndOutput_Group','打印',null,null,'1001A1100000001IYV0D',null,'Y','4004900H1_order_cjmMaster',39,'buttongroup','common','More',null,'','button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001J096P',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'Print','打印',null,null,'1001A1100000001IYV0D',null,'Y','4004900H1_order_cjmMaster',40,'general_btn','common','PrintAndOutput_Group',null,'Ctrl+P','button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001J096Q',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'Output','输出',null,null,'1001A1100000001IYV0D',null,'Y','4004900H1_order_cjmMaster',41,'general_btn','common','PrintAndOutput_Group',null,'Ctrl+W','button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001J096R',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'ImportAndExport_Group','导入',null,null,'1001A1100000001IYV0D',null,'Y','4004900H1_order_cjmMaster',42,'buttongroup','common','More',null,'','button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001J096T',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'Import','导入',null,null,'1001A1100000001IYV0D',null,'Y','4004900H1_order_cjmMaster',43,'general_btn','common','ImportAndExport_Group',null,'Ctrl+Alt+E','button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001J096U',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'Export','导出',null,null,'1001A1100000001IYV0D',null,'Y','4004900H1_order_cjmMaster',44,'general_btn','common','ImportAndExport_Group',null,'ctrl+alt+c','button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001J096V',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'BillTrack_Group','辅助功能',null,null,'1001A1100000001IYV0D',null,'Y','4004900H1_order_cjmMaster',45,'buttongroup','common','More',null,'','button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001J096X',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'ApproveDetail','审批详情',null,null,'1001A1100000001IYV0D',null,'Y','4004900H1_order_cjmMaster',46,'general_btn','common','BillTrack_Group',null,'Ctrl+O','button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001J096Y',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'BillTrack','单据追溯',null,null,'1001A1100000001IYV0D',null,'Y','4004900H1_order_cjmMaster',47,'general_btn','common','BillTrack_Group',null,'ctrl+k','button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001J096Z',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'Refresh','',null,null,'1001A1100000001IYV0D',null,'Y','4004900H1_order_cjmMaster',48,'general_btn','common',null,null,'F5','button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001J0970',0,null ) 
/

