insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'fs_group_add','新建分组',null,null,'1001A11LCP00001IZLJZ',null,'Y','4004900H1P_order_cjmMasterP',1,'general_btn','ncuploader_modal-area',null,null,null,'button_main',null,null,null,null,null,null,null,'1001A11LCP00001J08WC',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'fs_browse','预览',null,null,'1001A11LCP00001IZLJZ',null,'Y','4004900H1P_order_cjmMasterP',2,'general_btn','ncuploader_modal-area',null,null,null,'button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001J08WD',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'fs_delete','删除',null,null,'1001A11LCP00001IZLJZ',null,'Y','4004900H1P_order_cjmMasterP',3,'general_btn','ncuploader_modal-area',null,null,null,'button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001J08WE',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'fs_download','下载',null,null,'1001A11LCP00001IZLJZ',null,'Y','4004900H1P_order_cjmMasterP',4,'general_btn','ncuploader_modal-area',null,null,null,'button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001J08WF',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'fs_edit','修改',null,null,'1001A11LCP00001IZLJZ',null,'Y','4004900H1P_order_cjmMasterP',5,'general_btn','ncuploader_modal-area',null,null,null,'button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001J08WG',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'fs_group_edit','组名修改',null,null,'1001A11LCP00001IZLJZ',null,'Y','4004900H1P_order_cjmMasterP',6,'general_btn','ncuploader_modal-area',null,null,null,'button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001J08WH',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'fs_group_delete','组名删除',null,null,'1001A11LCP00001IZLJZ',null,'Y','4004900H1P_order_cjmMasterP',7,'general_btn','ncuploader_modal-area',null,null,null,'button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001J08WI',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'fs_heigh_meter','高拍仪',null,null,'1001A11LCP00001IZLJZ',null,'Y','4004900H1P_order_cjmMasterP',8,'general_btn','ncuploader_modal-area',null,null,null,'button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001J08WJ',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'fs_move','移动',null,null,'1001A11LCP00001IZLJZ',null,'Y','4004900H1P_order_cjmMasterP',9,'general_btn','ncuploader_modal-area',null,null,null,'button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001J08WK',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'fs_rename','重命名',null,null,'1001A11LCP00001IZLJZ',null,'Y','4004900H1P_order_cjmMasterP',10,'general_btn','ncuploader_modal-area',null,null,null,'button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001J08WL',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'fs_upload','上传',null,null,'1001A11LCP00001IZLJZ',null,'Y','4004900H1P_order_cjmMasterP',11,'general_btn','ncuploader_modal-area',null,null,null,'button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001J08WM',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'fs_upload_url','上传url',null,null,'1001A11LCP00001IZLJZ',null,'Y','4004900H1P_order_cjmMasterP',12,'general_btn','ncuploader_modal-area',null,null,null,'button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001J08WN',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'Edit','修改',null,null,'1001A11LCP00001IZLJZ',null,'Y','4004900H1P_order_cjmMasterP',1,'general_btn','common',null,null,'Alt+P','button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001J0972',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'Save','保存',null,null,'1001A11LCP00001IZLJZ',null,'Y','4004900H1P_order_cjmMasterP',2,'general_btn','common',null,null,'Ctrl+S','button_main',null,null,null,null,null,null,null,'1001A11LCP00001J0973',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'Cancel','取消',null,null,'1001A11LCP00001IZLJZ',null,'Y','4004900H1P_order_cjmMasterP',3,'general_btn','common',null,null,'Alt+Q','button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001J0974',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'Attachment','附件管理',null,null,'1001A11LCP00001IZLJZ',null,'Y','4004900H1P_order_cjmMasterP',4,'general_btn','common',null,null,'Alt+D','button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001J0975',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'Refresh','',null,null,'1001A11LCP00001IZLJZ',null,'Y','4004900H1P_order_cjmMasterP',5,'general_btn','common',null,null,'F5','button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001J0976',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'order_cjmSlave0_AddLine_Group','',null,null,'1001A11LCP00001IZLJZ',null,'Y','4004900H1P_order_cjmMasterP',6,'buttongroup','order_cjmSlave0',null,null,'','button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001J0977',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'order_cjmSlave0_AddLine','增行',null,null,'1001A11LCP00001IZLJZ',null,'Y','4004900H1P_order_cjmMasterP',7,'general_btn','order_cjmSlave0','order_cjmSlave0_AddLine_Group',null,'Alt+N','button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001J0978',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'order_cjmSlave0_CopyLine','复制',null,null,'1001A11LCP00001IZLJZ',null,'Y','4004900H1P_order_cjmMasterP',8,'general_btn','order_cjmSlave0','order_cjmSlave0_AddLine_Group',null,'alt+c','button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001J0979',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'order_cjmSlave0_DelLine','删行',null,null,'1001A11LCP00001IZLJZ',null,'Y','4004900H1P_order_cjmMasterP',9,'general_btn','order_cjmSlave0','order_cjmSlave0_AddLine_Group',null,'alt+del','button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001J097A',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'order_cjmSlave0_Past_Group','',null,null,'1001A11LCP00001IZLJZ',null,'Y','4004900H1P_order_cjmMasterP',10,'buttongroup','order_cjmSlave0',null,null,'','button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001J097B',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'order_cjmSlave0_PastEndLine','粘贴到末行',null,null,'1001A11LCP00001IZLJZ',null,'Y','4004900H1P_order_cjmMasterP',11,'general_btn','order_cjmSlave0','order_cjmSlave0_Past_Group',null,'Ctrl+Alt+V','button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001J097C',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'order_cjmSlave0_CopyCancelLine','取消',null,null,'1001A11LCP00001IZLJZ',null,'Y','4004900H1P_order_cjmMasterP',12,'general_btn','order_cjmSlave0','order_cjmSlave0_Past_Group',null,null,'button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001J097D',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'order_cjmSlave0_Opr_DelLine','删行',null,null,'1001A11LCP00001IZLJZ',null,'Y','4004900H1P_order_cjmMasterP',13,'general_btn','order_cjmSlave0_Opr',null,null,'alt+del','button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001J097E',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'order_cjmSlave0_Opr_ExpandLine','展开',null,null,'1001A11LCP00001IZLJZ',null,'Y','4004900H1P_order_cjmMasterP',14,'general_btn','order_cjmSlave0_Opr',null,null,'F4','button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001J097F',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'order_cjmSlave0_Opr_CopyLine','复制',null,null,'1001A11LCP00001IZLJZ',null,'Y','4004900H1P_order_cjmMasterP',15,'general_btn','order_cjmSlave0_Opr',null,null,'alt+c','button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001J097G',0,null ) 
/

insert into SM_APPBUTNREGISTER ( BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,PK_BTN,DR,TS ) values  ( 'order_cjmSlave0_Opr_PastNextLine','粘贴至此',null,null,'1001A11LCP00001IZLJZ',null,'Y','4004900H1P_order_cjmMasterP',16,'general_btn','order_cjmSlave0_Opr',null,null,'Alt+V','button_secondary',null,null,null,null,null,null,null,'1001A11LCP00001J097H',0,null ) 
/

