insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001A11LCP000007K054','Refresh','',null,null,'1001A11LCP000007K014',null,'Y','10880557P_testmdMasterP',1,'general_btn','common',null,null,'F5','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001A11LCP000007K055','testmdSlave0_AddLine_Group','',null,null,'1001A11LCP000007K014',null,'Y','10880557P_testmdMasterP',2,'buttongroup','testmdSlave0',null,null,'','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001A11LCP000007K056','testmdSlave0_AddLine','增行',null,null,'1001A11LCP000007K014',null,'Y','10880557P_testmdMasterP',3,'general_btn','testmdSlave0','testmdSlave0_AddLine_Group',null,'Alt+N','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001A11LCP000007K057','testmdSlave0_CopyLine','复制',null,null,'1001A11LCP000007K014',null,'Y','10880557P_testmdMasterP',4,'general_btn','testmdSlave0','testmdSlave0_AddLine_Group',null,'alt+c','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001A11LCP000007K058','testmdSlave0_DelLine','删行',null,null,'1001A11LCP000007K014',null,'Y','10880557P_testmdMasterP',5,'general_btn','testmdSlave0','testmdSlave0_AddLine_Group',null,'alt+del','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001A11LCP000007K059','testmdSlave0_Past_Group','',null,null,'1001A11LCP000007K014',null,'Y','10880557P_testmdMasterP',6,'buttongroup','testmdSlave0',null,null,'','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001A11LCP000007K05A','testmdSlave0_PastEndLine','粘贴到末行',null,null,'1001A11LCP000007K014',null,'Y','10880557P_testmdMasterP',7,'general_btn','testmdSlave0','testmdSlave0_Past_Group',null,'Ctrl+Alt+V','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001A11LCP000007K05B','testmdSlave0_CopyCancelLine','取消',null,null,'1001A11LCP000007K014',null,'Y','10880557P_testmdMasterP',8,'general_btn','testmdSlave0','testmdSlave0_Past_Group',null,null,'button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001A11LCP000007K05C','testmdSlave0_Opr_DelLine','删行',null,null,'1001A11LCP000007K014',null,'Y','10880557P_testmdMasterP',9,'general_btn','testmdSlave0_Opr',null,null,'alt+del','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001A11LCP000007K05D','testmdSlave0_Opr_ExpandLine','展开',null,null,'1001A11LCP000007K014',null,'Y','10880557P_testmdMasterP',10,'general_btn','testmdSlave0_Opr',null,null,'F4','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001A11LCP000007K05E','testmdSlave0_Opr_CopyLine','复制',null,null,'1001A11LCP000007K014',null,'Y','10880557P_testmdMasterP',11,'general_btn','testmdSlave0_Opr',null,null,'alt+c','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001A11LCP000007K05F','testmdSlave0_Opr_PastNextLine','粘贴至此',null,null,'1001A11LCP000007K014',null,'Y','10880557P_testmdMasterP',12,'general_btn','testmdSlave0_Opr',null,null,'Alt+V','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

